run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck    # Проверяет, что ошибки не игнорируются
    - gofmt       # Проверяет стандартное форматирование кода
    - govet       # Стандартный анализатор Go
    - staticcheck # Анализатор логических ошибок и мертвого кода
    - gosimple    # Подсказывает, как упростить код
    - ineffassign # Находит переменные, которым присвоили значение, но не использовали
    - gosec       # Проверяет код на уязвимости безопасности
    - gocritic    # Набор проверок на лучшие практики производительности и стиля

issues:
  exclude-use-default: false