name: Backend Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  push:
    branches: [ "**" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'
          cache-dependency-path: backend/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend
          install-mode: goinstall

      - name: Run tests
        run: go test -v ./...

      - name: Build check
        run: go build -v ./...